[package]
name = "tor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]


[dependencies]
anyhow = "1.0.89"
arti-client = { version = "0.23.0", features = ["rustls", "tokio", "static"], default-features = false }
jni = { version = "0.19", default-features = false }
tokio = { version = "1.0", features = ["rt", "macros"] }
